### ISSUE TITLE
Checklist for 2.0

### ISSUE THREAD

**Issue by DrChainsaw** [DrChainsaw/NaiveNASflux.jl#69]
[Rel 2 of NaiveNASlib](https://github.com/DrChainsaw/NaiveNASlib.jl/issues/86) will force a rel 2 due to reexport. Just as with NaiveNASlib, I plan to be quite liberal with breakage. Let me know if you are a user and would prefer less breakage.

Other things to fix:

- [x] Rename `mutable` to `fluxvertex` (wtf was I thinking?!).
- [x] Don't reexport Flux.
- [x] Greatly reduce the amount of exported functions and types.
- [x] Merge #53.
- [x] Make all layerwrappers real functors instead of relying on mutation (if possible).
- [x] Rename neuron_value to neuronutility (same for types affecting its behaviour)
